kind: project
metadata:
  name: tsaa-ap-git-test
  created: '2024-06-10T07:55:01.817000'
spec:
  functions: []
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/GiladShapira94/simple-remote.git
  load_source_on_run: true
  desired_state: online
  owner: shapira
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
